version: '3.9'

services:
  web:
    build: ./CTF_management
    container_name: my-web-api
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - ctf-net

  celery:
    build: ./CTF_management
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
    container_name: my-celery
    command: celery -A account_app.utils worker --loglevel=info
    depends_on:
      - redis
    networks:
      - ctf-net

  postgres:
    image: docker.arvancloud.ir/postgres
    container_name: my-postgres
    environment:
      POSTGRES_USER: ctf_admin
      POSTGRES_PASSWORD: ctf_admin
      POSTGRES_DB: ctfdb
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ctf-net

  redis:
    image: docker.arvancloud.ir/redis
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - ctf-net

volumes:
  pgdata:

networks:
  ctf-net:
    driver: bridge
